### ISSUE TITLE
Test fails on moar-2022.04

### ISSUE THREAD

**Issue by 2colours** [lizmat/Git-Blame-File#1]
Hello,

while trying to install the module as a dependency of App::Rak, I got the following test error:

===> Testing: Git::Blame::File:ver<0.0.2>:auth<zef:lizmat>
[Git::Blame::File] No such method 'Failure' for invocant of type 'Str'
[Git::Blame::File]   in method TWEAK at ...../Git-Blame-File-0.0.2/lib/Git/Blame/File.rakumod (Git::Blame::File) line 150
[Git::Blame::File]   in method new at ...../Git-Blame-File-0.0.2/lib/Git/Blame/File.rakumod (Git::Blame::File) line 71
[Git::Blame::File]   in block <unit> at t/01-basic.rakutest line 6
===> Testing [FAIL]: Git::Blame::File:ver<0.0.2>:auth<zef:lizmat>

**Comment by lizmat** [comment]
Which version of Rakudo are you using?

**Comment by lizmat** [comment]
Probably an older one.  I've uploaded 0.03 to fez, and bumped App::Rak accordingly.

Please close if this fixes it.

**Comment by 2colours** [comment]
Still fails but differently, this seems like a semantic issue:

[Git::Blame::File] # Failed test 'The object is-a 'Git::Blame::File''
[Git::Blame::File] # at t/01-basic.rakutest line 7
[Git::Blame::File] # Actual type: Failure
[Git::Blame::File] fatal: not a git repository (or any parent up to mount point /)
[Git::Blame::File] Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[Git::Blame::File]   in method TWEAK at /home/ASTRON-INF/pm7342/.zef/tmp/49915d7d259c830a3f854b618cfbe99c26218bb2.tar.gz/Git-Blame-File-0.0.3/lib/Git/Blame/File.rakumod (Git::Blame::File) line 149
[Git::Blame::File]   in method new at /home/ASTRON-INF/pm7342/.zef/tmp/49915d7d259c830a3f854b618cfbe99c26218bb2.tar.gz/Git-Blame-File-0.0.3/lib/Git/Blame/File.rakumod (Git::Blame::File) line 71
[Git::Blame::File]   in block <unit> at t/01-basic.rakutest line 6
[Git::Blame::File] Actually thrown at:
[Git::Blame::File]   in block <unit> at t/01-basic.rakutest line 9

**Comment by lizmat** [comment]
Nope, it was a stupid thinko on my part.  I always installed from the dir in which I develop the module.  Which is in a git repo.  So locally, the tests worked.  But not if downloaded from a tar file, that **doesn't** have the git info.  Duh.  And of course, in Github Actions, it just clones the repo, so there the tests worked also.

I've moved the tests to the `xt` directory, so I'll only run them locally.

Thanks for persisting.  `zef update` and `zef install Git::Blame::File` and all should be fine.  Please close if you concur :-)

**Comment by 2colours** [comment]
Well yes, that's what I meant with semantics. :P Anyway, it works now indeed. :) Thanks for the quick response, closing this issue.
